version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.15.0
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: node --version
      - run: npm install
      - run: npx sls --version
      - run: npx sls deploy --stage stg --verbose

  test:
    docker:
      - image: cimg/node:18.15.0
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test